### ISSUE TITLE
It seems I have a short proof of P=NP - check it

### ISSUE THREAD

**Issue by vporton** [leanprover/lean4-nightly#1]
I've produced a short and much elementary proof of P=NP (without an efficient algorithm presented). I sent it to a reputable CS journal and insofar there were no errors noticed by the editor. (However, I myself found several errors, that are already corrected in the attached file.)

You should check my proof.

[p=np-merkle.pdf](https://github.com/leanprover/lean4-nightly/files/6725186/p.np-merkle.pdf)

**Comment by vporton** [comment]
https://math.portonvictor.org/2021/06/28/a-proof-of-pnp-using-a-merkle-tree-a-new-version/ for updated, more detailed proof.

**Comment by leodemoura** [comment]
The issues tracker for the Lean nightly builds is not an appropriate place for reviewing or discussing this kind of result.

**Comment by vporton** [comment]
@leodemoura I mean to include the result into the Lean library (that is verify formally). What else could I mean?

Discussion of incuding into Lean library is not appropriate for discussing in nightly builds?

**Comment by vvs-** [comment]
Please, don't take it personally. No interactive theorem prover should be seen as a research institution. Take your own research to a peer reviewed magazine instead. Or create a _formal_ proof in Lean yourself.

That's a policy which should be followed by any researcher. Sorry.
